OPENAI_ORGANIZATION = 'MY_API_KEY'
OPENAI_API_KEY = 'MY_API_KEY'

AZURE_API_KEY = 'MY_API_KEY'
AZURE_API_KEY_2 = 'MY_API_KEY2'
AZURE_OPENAI_ENDPOINT = 'MY_ENDPOINT'
AZURE_OPENAI_ENDPOINT_2 = 'MY_ENDPOINT2'

TOGETHER_API_KEY = 'MY_API_KEY'
GOOGLE_API_KEY = 'MY_API_KEY'

GOOGLE_PROJECT = 'MY_PROJECT'
GOOGLE_LOCATION = 'us-west1'
